### ISSUE TITLE
Warnings on certain Signer List scenario's (when setting up the SignerList)

### ISSUE THREAD

**Issue by WietseWind** [WietseWind/XRPL-MultiSignTool#4]
This scenario results in lost funds when only one key is lost.

**Comment by alloyxrp** [comment]
Maybe a warning if any **one** signer weight = quorum ?

**Comment by WietseWind** [comment]
@alloyxrp That's a good one as well. So, some warnings in general.

- Warning if Weight Sum === Quorum
- Warning if a single signer === Quorum (although I can think of use cases for this one, but people need to consider it another time, indeed)

Thanks 👍

**Comment by alloyxrp** [comment]
Also a warning in the unlikely situation where single signer weight > quorum. Or a single signer weight can never be > quorum.

**Comment by WietseWind** [comment]
- Warning if Weight Sum === Quorum
- Warning if a single signer === Quorum (although I can think of use cases for this one, but people need to consider it another time, indeed)
- Single Signer weight > Quorum

**Comment by WietseWind** [comment]
![XRP stats](https://user-images.githubusercontent.com/4756161/54867286-da961e00-4d7e-11e9-98d1-83a617e0b89f.gif)
