### ISSUE TITLE
cant setup multisigning

### ISSUE THREAD

**Issue by popnop** [WietseWind/XRPL-MultiSignTool#5]
after adding the accounts on test net there is no " now go offline"
![multi](https://user-images.githubusercontent.com/51814157/59979350-66724d00-95ef-11e9-8ae2-8b4f6a026785.PNG)

**Comment by WietseWind** [comment]
Hey! Looks like it doesn't continue because the three accounts don't validate. They are red (signer list). Sure you didn't copy-paste additional spaces or something? If the accounts validate the next steps should automatically appear.

**Comment by popnop** [comment]
thanks i can see the go offline i disconnected my Ethernet cable   ( the pc is offline ) 
how do i get the box to enter the secret key  
i try on both clud and zip file  ( chrome and firefox ) 
![OFF](https://user-images.githubusercontent.com/51814157/59994303-036acf80-965c-11e9-81f6-8a517614446a.PNG)
![go](https://user-images.githubusercontent.com/51814157/59994305-05349300-965c-11e9-9009-dc6c496aa30b.PNG)

**Comment by WietseWind** [comment]
Did you solve the initial question with my response?

And: sure you are completely offline, not perhaps another connection like Wifi still active?

You could try putting Firefox manually in offline mode. This property (offline detection) is updated whenever the user switches into "Offline Mode" by selecting the corresponding menu item (File -> Work Offline in Firefox).

Additionally, this property should update whenever a browser is no longer capable of connecting to the network. According to the specification:

**Comment by popnop** [comment]
ok using firefox offline mode  works perfect :)   but not when disconnecting wifi or the cable ( there is a bug )    
this is an **amazing tool** 
1. how can i verify that my master key is disabled?
2. if for some reason this tool is not available how can i get access to accounts that are multisigin
3. will there be any UI improvements ? 
thanks for all the hard work !!!

**Comment by WietseWind** [comment]
Awesome, thanks. I'll see if I can listen to another event for FF to detect online/offline. What's your OS+Version so I can try to reproduce and fix it?

1. You can see it with an explorer like (sample): https://bithomp.com/explorer/rPdvC6ccq8hCdPKSPJkPmyZ4Mi1oG2FFkT: the account details will show that the master key is disabled and a regular key is set.
2. The tool will be available ;) And I'm sure more and more clients will add multi signing in the near future.
3. This tool: no, but some devs in the community are working on awesome tools with multi sign support 😇 

My pleasure!

**Comment by popnop** [comment]
Os-Win 10
Chrome and firefox newest version




בתאריך יום ב׳, 24 ביוני 2019, 11:47, מאת Wietse Wind ‏<
notifications@github.com>:
